/*
Counting Point Mutations
https://rosalind.info/problems/hamm/
*/

fn hamming_distance(s: &str, t: &str) -> usize {
    let mut sc = s.chars();
    let mut tc = t.chars();
    let mut count = 0;
    loop {
        match (sc.next(), tc.next()) {
            (Some(x), Some(y)) => if x != y { count += 1},
            (Some(_), None) | (None, Some(_)) => count += 1,
            (None, None) => return count
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::hamm::hamming_distance;

    #[test]
    fn it_works() {
        let s = "GAGCCTACTAACGGGAT";
        let t = "CATCGTAATGACGGCCT";
        assert_eq!(7, hamming_distance(s, t));
    }

    #[test]
    fn actual_dataset() {
        let s = "CCATCTTTCGAGGGAGATGTGACGTCGCGGAATTGGGGGATTCAGGCATCTCAAAGGACCAGCACACACCTGGGTATTCAGTCCACTGCCCCTGCTCTGTGTCATCCTGCTTCTAGCATCAGTACCGTTGCGATTCAATCGAAGGGAAGCATTCAGGGCGGATTCATGCGCCGTGTCGGTAATAGGCATATGGGAGACAGTTTGTGAATTCTGGATTGTGTAGTCAGTAGTTAGCTGTACTGACATATGGCTCTGTCCGCTGGAACAGGAGGTGATAGCTTGTTTCGCCTAGTGGCCACATTCTAGGCCTAGGGGAACGGAGATCATTCTTTGGGCTCACCACAGTGGAGCTAGTGCTTTTCCGCTCCACTGCAGTGCAATCAAGTTTAAAACGGGAGTAAGCCGCAGTGTGACCCCTGTTTGGCTTGGGCGGAGTTTATTACTTCCTACCTCACACCGCTGAAGGTTATTCTGACATGCCGCTTTTACAGCCGTTAAGCAGCTCTTATACTCTCAATCGCCGGGTAAAAAATTACGCAGCTTAAAACTACGCTTTACTACTTGTGGCTATCAGTGGTTTTAGCTGCGTGGATTCACTCTTGATAGAATGAAATCTATGTGGAGCAATCCGGCCTGATACCAGGAACGACGGCGAGTTAGCTACGCGAAGATGGGTTAGTGAGACCTAGACTGTGTTCCGGGGATCCTAGAGTCGTCGCGTGGCTATCGGATCGTAAAGGCAAGCCTGCTGACATTCTAGCCGTTAGAAAAGAGTTAACTCCGCTGGTTCCCAAGTGTGCAAGAATCTCCCTTGTGGACGCCATTCGGGTATAATTTTCAGTATCCTGGGTGCCAGAAGTCGAAACAGGCCTCTCCAGTCTTGTGCGGATTGTCATCGTTGACCGAAGTTCCTCCCCTGATGGTATTCCCTTGTAACACGGTTCATGCTTACTCTGCCGATGGGCCGTAGTTTCGCCGGAGAAGTTGGAT";
        let t = "ATTCCTGGCGAGGGTGAAATCAACTGGTCGGGTTCAGGCGTTACACTCTCTTCGTTCATGGGGTATCAACATGCTTAACAGTTCTCCCTAGATCCGATAAGGCTTTTCGGCTTTACCAGAGGGCCTGTTCCGCCTCTCACCCCTGATACCACTTACCGAAGAGTCATGCGCGGTGTCACGAAAAAAAATATACATGCCAGCTTACTTAGCTCGGTACCAGGAAAAGTGAGCTATTTGCATGAACGCGAGACTTTGTTCGCTGGTACAGAGGTTTAGGTCTCGCCAAGGTAGGTGGCGTCTACGGGAGCCACATGTATGGCAATCACGTCCCTGGTGTCTATTCTGTGAAGCTGCCCTGTATCCGCGGCACGTACCCGCTCTTTAGTGAAGAATGGCCCAAAGTACCAGTCGGAAGGATCTCTTTCGTGGTGTCCGCTATCTGGTCCCTGTCGAGAGCCACTGTATCTCAGTTTGGTATGCGCTTTTTACCTCGTCTCAGCTGATCCTAGACCCTACGTCGCGCGGTTATAAACTATACACTTGCCGATTCCTCCCTAGTCTCTTAGACAGAAAGCCTTAGGAGCTGCTTGGATCAGGGAATTAACCGATAACTCGAACAGGGAACTGGCTGGCCAAACGTCCTGAGCCTCGTGACGCTTTAATGGGGACAACACGTAAGTGGCACGTGGCCTGTCTTTTGGGGAACCTAGACGTGTGGGATTGCGTCCGAATATGATGTGCAAATGTCACCTAGTTCGAAGTGTTCCTACCGATCCTCGTCCGATGATAAACTGGTGTGTGGAATTCCCGCAGTGCAATTACACTTGGGTAAGGCGTGCAGTATGGTCGCTGCCAGGAATGGAAACACTGCTTTAGAGCGGTCATAGTGGCAAGAGCGCTTATATTCGGGCGTTCCACGTCATAAGACCATTGTTATATATTTAAGGCCAAAGCTTCCGTTGTTGCTCCGGTGTGACTGCTAAGTCGAAT";
        println!("{}", hamming_distance(s, t));
        // Correct answer: 528
    }
}